env:
  global:
    - CC_TEST_REPORTER_ID=2aca912cde2600600d026ce6dc620a802bc392f63f4ad9a4a8316ed180b6fc37

language: node_js

rvm:
  - 2.2.0

node_js:
  - node

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - make lint
  - make test
  - make test-coverage

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
